# Generated by Django 4.2.9 on 2026-02-15 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("magasins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_action",
                    models.CharField(
                        choices=[
                            ("PRODUIT_CREE", "Produit créé"),
                            ("PRODUIT_MODIFIE", "Produit modifié"),
                            ("PRODUIT_SUPPRIME", "Produit supprimé"),
                            ("MAGASIN_CREE", "Magasin créé"),
                            ("MAGASIN_MODIFIE", "Magasin modifié"),
                            ("MAGASIN_SUPPRIME", "Magasin supprimé"),
                            ("STOCK_REAPPROVISIONNE", "Stock réapprovisionné"),
                            ("STOCK_TRANSFERE", "Stock transféré"),
                            ("STOCK_AJUSTE", "Stock ajusté"),
                            ("VENTE_EFFECTUEE", "Vente effectuée"),
                            ("VENTE_ANNULEE", "Vente annulée"),
                            ("UTILISATEUR_CREE", "Utilisateur créé"),
                            ("UTILISATEUR_MODIFIE", "Utilisateur modifié"),
                            ("UTILISATEUR_SUPPRIME", "Utilisateur supprimé"),
                            ("CATEGORIE_CREEE", "Catégorie créée"),
                            ("CATEGORIE_MODIFIEE", "Catégorie modifiée"),
                            ("CATEGORIE_SUPPRIMEE", "Catégorie supprimée"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="type d'action",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(verbose_name="description")),
                (
                    "donnees_avant",
                    models.JSONField(
                        blank=True,
                        help_text="État des données avant l'action",
                        null=True,
                        verbose_name="données avant",
                    ),
                ),
                (
                    "donnees_apres",
                    models.JSONField(
                        blank=True,
                        help_text="État des données après l'action",
                        null=True,
                        verbose_name="données après",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informations supplémentaires sur l'action",
                        verbose_name="métadonnées",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adresse IP"
                    ),
                ),
                (
                    "date_action",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date de l'action",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historique",
                        to="magasins.magasin",
                        verbose_name="magasin",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historique_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique",
                "verbose_name_plural": "historiques",
                "ordering": ["-date_action"],
                "indexes": [
                    models.Index(
                        fields=["-date_action"], name="historique__date_ac_41a336_idx"
                    ),
                    models.Index(
                        fields=["type_action", "-date_action"],
                        name="historique__type_ac_756121_idx",
                    ),
                    models.Index(
                        fields=["utilisateur", "-date_action"],
                        name="historique__utilisa_7c2edc_idx",
                    ),
                    models.Index(
                        fields=["magasin", "-date_action"],
                        name="historique__magasin_2f16d4_idx",
                    ),
                ],
            },
        ),
    ]
