# Generated by Django 4.2.9 on 2026-02-15 22:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_categories",
                        to="produits.categorie",
                        verbose_name="catégorie parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="nom du produit"),
                ),
                (
                    "code_barre",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="code-barres",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="référence interne",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stockage des caractéristiques techniques du produit",
                        verbose_name="spécifications techniques",
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="prix d'achat",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="prix de vente",
                    ),
                ),
                (
                    "unite_mesure",
                    models.CharField(
                        choices=[
                            ("PIECE", "Pièce"),
                            ("KG", "Kilogramme"),
                            ("G", "Gramme"),
                            ("L", "Litre"),
                            ("ML", "Millilitre"),
                            ("M", "Mètre"),
                            ("CM", "Centimètre"),
                            ("CARTON", "Carton"),
                            ("PACK", "Pack"),
                        ],
                        default="PIECE",
                        max_length=10,
                        verbose_name="unité de mesure",
                    ),
                ),
                (
                    "seuil_alerte",
                    models.IntegerField(
                        default=10,
                        help_text="Niveau de stock minimum avant alerte",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="seuil d'alerte",
                    ),
                ),
                (
                    "stock_minimal",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="stock minimal",
                    ),
                ),
                (
                    "stock_maximal",
                    models.IntegerField(
                        default=1000,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="stock maximal",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="produits/",
                        verbose_name="image",
                    ),
                ),
                (
                    "poids",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="poids (kg)",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="dimensions (L x l x H)",
                    ),
                ),
                (
                    "fournisseur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="fournisseur"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "is_perishable",
                    models.BooleanField(default=False, verbose_name="périssable"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produits",
                        to="produits.categorie",
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produits_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "produit",
                "verbose_name_plural": "produits",
                "ordering": ["nom"],
                "indexes": [
                    models.Index(
                        fields=["code_barre"], name="produits_pr_code_ba_6aba8a_idx"
                    ),
                    models.Index(
                        fields=["reference"], name="produits_pr_referen_0972d6_idx"
                    ),
                    models.Index(
                        fields=["categorie"], name="produits_pr_categor_b80ae3_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="categorie",
            index=models.Index(fields=["code"], name="produits_ca_code_974e9e_idx"),
        ),
    ]
