# Generated by Django 4.2.9 on 2026-02-19 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="seuil_alerte",
            field=models.IntegerField(
                default=5,
                help_text="Niveau de stock minimum avant alerte",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="seuil d'alerte",
            ),
        ),
    ]
