# Generated by Django 4.2.9 on 2026-02-15 22:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Magasin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="nom du magasin"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code doit contenir uniquement des lettres majuscules et des chiffres",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                        verbose_name="code magasin",
                    ),
                ),
                ("adresse", models.TextField(verbose_name="adresse")),
                ("ville", models.CharField(max_length=100, verbose_name="ville")),
                (
                    "pays",
                    models.CharField(
                        default="Bénin", max_length=100, verbose_name="pays"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="téléphone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="surface (m²)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="magasins_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "magasin",
                "verbose_name_plural": "magasins",
                "ordering": ["nom"],
                "indexes": [
                    models.Index(fields=["code"], name="magasins_ma_code_28bd33_idx"),
                    models.Index(fields=["ville"], name="magasins_ma_ville_c0779c_idx"),
                ],
            },
        ),
    ]
