# Generated by Django 4.2.9 on 2026-02-19 15:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("magasins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_vente",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="numéro de vente",
                    ),
                ),
                (
                    "nom_client",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nom du client"
                    ),
                ),
                (
                    "telephone_client",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone client"
                    ),
                ),
                (
                    "email_client",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email client"
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="montant total",
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="montant payé",
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="remise",
                    ),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("CARTE", "Carte bancaire"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CHEQUE", "Chèque"),
                            ("VIREMENT", "Virement"),
                        ],
                        max_length=20,
                        verbose_name="méthode de paiement",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("VALIDEE", "Validée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_COURS",
                        max_length=15,
                        verbose_name="statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "est_annulee",
                    models.BooleanField(default=False, verbose_name="annulée"),
                ),
                (
                    "date_annulation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date d'annulation"
                    ),
                ),
                (
                    "motif_annulation",
                    models.TextField(blank=True, verbose_name="motif d'annulation"),
                ),
                (
                    "date_vente",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date de vente"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "annulee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes_annulees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="annulée par",
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes",
                        to="magasins.magasin",
                        verbose_name="magasin",
                    ),
                ),
                (
                    "vendeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes_effectuees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vendeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "vente",
                "verbose_name_plural": "ventes",
                "ordering": ["-date_vente"],
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="prix unitaire",
                    ),
                ),
                (
                    "remise_ligne",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="remise sur la ligne",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_vente",
                        to="produits.produit",
                        verbose_name="produit",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="ventes.vente",
                        verbose_name="vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de vente",
                "verbose_name_plural": "lignes de vente",
                "ordering": ["vente", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["numero_vente"], name="ventes_vent_numero__37427b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["magasin", "-date_vente"], name="ventes_vent_magasin_a9a563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(fields=["statut"], name="ventes_vent_statut_4c1c73_idx"),
        ),
    ]
