# Generated by Django 4.2.9 on 2026-02-15 22:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ventes", "0001_initial"),
        ("magasins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="quantité en stock",
                    ),
                ),
                (
                    "quantite_reservee",
                    models.IntegerField(
                        default=0,
                        help_text="Quantité réservée pour des commandes en attente",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="quantité réservée",
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Rayon A, Étagère 3",
                        max_length=100,
                        verbose_name="emplacement",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "last_inventory_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier inventaire"
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="magasins.magasin",
                        verbose_name="magasin",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="produits.produit",
                        verbose_name="produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock",
                "verbose_name_plural": "stocks",
                "ordering": ["magasin", "produit"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée"),
                            ("SORTIE", "Sortie"),
                            ("TRANSFERT", "Transfert"),
                            ("AJUSTEMENT", "Ajustement"),
                            ("RETOUR", "Retour"),
                        ],
                        max_length=15,
                        verbose_name="type de mouvement",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantité",
                    ),
                ),
                ("quantite_avant", models.IntegerField(verbose_name="quantité avant")),
                ("quantite_apres", models.IntegerField(verbose_name="quantité après")),
                ("motif", models.TextField(blank=True, verbose_name="motif")),
                (
                    "reference_document",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="référence document"
                    ),
                ),
                (
                    "date_mouvement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date du mouvement"
                    ),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_effectues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="effectué par",
                    ),
                ),
                (
                    "magasin_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_entrants",
                        to="magasins.magasin",
                        verbose_name="magasin de destination",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="stocks.stock",
                        verbose_name="stock",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock",
                        to="ventes.vente",
                        verbose_name="vente associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement de stock",
                "verbose_name_plural": "mouvements de stock",
                "ordering": ["-date_mouvement"],
            },
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["produit", "magasin"], name="stocks_stoc_produit_d60b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["magasin"], name="stocks_stoc_magasin_5edc51_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("produit", "magasin")},
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["stock", "-date_mouvement"],
                name="stocks_mouv_stock_i_bd56d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["type_mouvement"], name="stocks_mouv_type_mo_a67d33_idx"
            ),
        ),
    ]
